services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=company_derectory
    networks:
      - company_derectory_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d company_derectory"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - company_derectory_network

networks:
  company_derectory_network:

volumes:
  pg_data: